/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
import javax.swing.JFrame;
public class MENU extends javax.swing.JFrame {
private String role;
    /**
     * Creates new form MENU
     */
    public MENU(String role) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("HOSPITAL LOGIN");
       this.role = role;
    setupRoleAccess();
    }
    private void setupRoleAccess() {
    switch(role.toLowerCase()) {
        case "admin":
            // Admin sees everything, do nothing
            break;

        case "doctor":
            // Doctor sees only relevant tables
            menuPatients.setEnabled(true);
            menuMedicalRecords.setEnabled(true);
            menuAppointments.setEnabled(true);

            menuOtherStaff.setEnabled(false);
            menuBilling.setEnabled(false);
            break;

        case "other_staff":
            // Other staff sees only limited tables
            menuAppointments.setEnabled(true);
            menuPatients.setEnabled(true);

            menuMedicalRecords.setEnabled(false);
            menuBilling.setEnabled(false);
            menuOtherStaff.setEnabled(false);
            break;

        case "patient":
            // Patient sees only their own data
            menuAppointments.setEnabled(true);

            menuPatients.setEnabled(false);
            menuMedicalRecords.setEnabled(false);
            menuBilling.setEnabled(false);
            menuOtherStaff.setEnabled(false);
            break;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPatients = new javax.swing.JMenuItem();
        menuOtherStaff = new javax.swing.JMenuItem();
        menuAppointments = new javax.swing.JMenuItem();
        menuLab = new javax.swing.JMenuItem();
        menuPharmacy = new javax.swing.JMenuItem();
        menuPrescription = new javax.swing.JMenuItem();
        menuBilling = new javax.swing.JMenuItem();
        menuWards = new javax.swing.JMenuItem();
        menuDoctors = new javax.swing.JMenuItem();
        menuMedicalRecords = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        pharmacyReports = new javax.swing.JMenuItem();
        AppointmentsReport = new javax.swing.JMenuItem();
        DoctorsReport = new javax.swing.JMenuItem();
        LabsReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("hospital data");

        menuPatients.setText("Patients");
        menuPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPatientsActionPerformed(evt);
            }
        });
        jMenu1.add(menuPatients);

        menuOtherStaff.setText("Other_Staff ");
        menuOtherStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOtherStaffActionPerformed(evt);
            }
        });
        jMenu1.add(menuOtherStaff);

        menuAppointments.setText("Appointments");
        menuAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAppointmentsActionPerformed(evt);
            }
        });
        jMenu1.add(menuAppointments);

        menuLab.setText(" Lab_Tests  ");
        menuLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLabActionPerformed(evt);
            }
        });
        jMenu1.add(menuLab);

        menuPharmacy.setText("  Pharmacy ");
        menuPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPharmacyActionPerformed(evt);
            }
        });
        jMenu1.add(menuPharmacy);

        menuPrescription.setText("Prescriptions  ");
        menuPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrescriptionActionPerformed(evt);
            }
        });
        jMenu1.add(menuPrescription);

        menuBilling.setText("  Billing  ");
        menuBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBillingActionPerformed(evt);
            }
        });
        jMenu1.add(menuBilling);

        menuWards.setText("  Wards_Rooms");
        menuWards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWardsActionPerformed(evt);
            }
        });
        jMenu1.add(menuWards);

        menuDoctors.setText("Doctors");
        menuDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDoctorsActionPerformed(evt);
            }
        });
        jMenu1.add(menuDoctors);

        menuMedicalRecords.setText("Medical Records");
        menuMedicalRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMedicalRecordsActionPerformed(evt);
            }
        });
        jMenu1.add(menuMedicalRecords);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("reports section");

        pharmacyReports.setText("Pharmacy Report");
        pharmacyReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacyReportsActionPerformed(evt);
            }
        });
        jMenu2.add(pharmacyReports);

        AppointmentsReport.setText("Appointments Report");
        AppointmentsReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentsReportActionPerformed(evt);
            }
        });
        jMenu2.add(AppointmentsReport);

        DoctorsReport.setText("Doctors Report");
        jMenu2.add(DoctorsReport);

        LabsReport.setText("Labs Report");
        jMenu2.add(LabsReport);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDoctorsActionPerformed
        // TODO add your handling code here:
        doctorsFrame doctors = new doctorsFrame();
        doctors.setLocationRelativeTo(this);
        doctors.setVisible(true);
    }//GEN-LAST:event_menuDoctorsActionPerformed

    private void menuPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPatientsActionPerformed
        // TODO add your handling code here:
         patientsFrame patients = new patientsFrame();
        patients.setLocationRelativeTo(this);
        patients.setVisible(true);
    }//GEN-LAST:event_menuPatientsActionPerformed

    private void menuOtherStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOtherStaffActionPerformed
        // TODO add your handling code here:
         otherstaffFrame otherstaff = new otherstaffFrame();
        otherstaff.setLocationRelativeTo(this);
        otherstaff.setVisible(true);
    }//GEN-LAST:event_menuOtherStaffActionPerformed

    private void menuAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAppointmentsActionPerformed
        // TODO add your handling code here:
        appointmentsFrame appointments = new appointmentsFrame();
        appointments.setLocationRelativeTo(this);
        appointments.setVisible(true);
    }//GEN-LAST:event_menuAppointmentsActionPerformed

    private void menuLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLabActionPerformed
        // TODO add your handling code here:
        labsFrame labs = new labsFrame();
        labs.setLocationRelativeTo(this);
        labs.setVisible(true);
    }//GEN-LAST:event_menuLabActionPerformed

    private void menuPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPharmacyActionPerformed
        // TODO add your handling code here:
        pharmacyFrame pharmacy = new pharmacyFrame();
        pharmacy.setLocationRelativeTo(this);
        pharmacy.setVisible(true);
    }//GEN-LAST:event_menuPharmacyActionPerformed

    private void menuPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrescriptionActionPerformed
        // TODO add your handling code here:
         prescriptionFrame prescription = new prescriptionFrame();
        prescription.setLocationRelativeTo(this);
        prescription.setVisible(true);
    }//GEN-LAST:event_menuPrescriptionActionPerformed

    private void menuBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBillingActionPerformed
        // TODO add your handling code here:
        billingFrame billing = new billingFrame();
        billing.setLocationRelativeTo(this);
        billing.setVisible(true);
    }//GEN-LAST:event_menuBillingActionPerformed

    private void menuWardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWardsActionPerformed
        // TODO add your handling code here:
       wardsFrame wards = new wardsFrame();
        wards.setLocationRelativeTo(this);
        wards.setVisible(true);
    }//GEN-LAST:event_menuWardsActionPerformed

    private void menuMedicalRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMedicalRecordsActionPerformed
        // TODO add your handling code here:
          medicalrecordsFrame records = new medicalrecordsFrame();
        records.setLocationRelativeTo(this);
        records.setVisible(true);
    }//GEN-LAST:event_menuMedicalRecordsActionPerformed

    private void pharmacyReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacyReportsActionPerformed
        // TODO add your handling code here:
         try {
        new PharmacyReport().createPdf();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_pharmacyReportsActionPerformed

    private void AppointmentsReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentsReportActionPerformed
        // TODO add your handling code here:
             try {
        new AppointmentsReport().createPdf();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_AppointmentsReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU("String role").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AppointmentsReport;
    private javax.swing.JMenuItem DoctorsReport;
    private javax.swing.JMenuItem LabsReport;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAppointments;
    private javax.swing.JMenuItem menuBilling;
    private javax.swing.JMenuItem menuDoctors;
    private javax.swing.JMenuItem menuLab;
    private javax.swing.JMenuItem menuMedicalRecords;
    private javax.swing.JMenuItem menuOtherStaff;
    private javax.swing.JMenuItem menuPatients;
    private javax.swing.JMenuItem menuPharmacy;
    private javax.swing.JMenuItem menuPrescription;
    private javax.swing.JMenuItem menuWards;
    private javax.swing.JMenuItem pharmacyReports;
    // End of variables declaration//GEN-END:variables
}
